# Site Information
license:          "MIT"
license-url:      "https://github.com/blairanderson/tachyonstemplates/blob/master/LICENSE"

# UPDATE THESE!
author:           "ApeAttack"
title:            Ape Attack
headline:         "Ape Attack"
subheadline:      "Apes don't Pounce. We Attack"
subheadline2:      "5 Million Apes. A Single Share Each. One Second"
subheadline3:      "5 Million Apes. A Single Share Each. One Second"
google-analytics: "G-VF2NQMSQ5H"

# Site Settings
baseurl:          ""
# Build settings
exclude:          [
  node_modules,
  sass-cache,
  _data,
  _components,
]
whitelist:
  - jekyll-redirect-from
# Dependencies
markdown:         kramdown
kramdown:
  # use Github Flavored Markdown
  input: GFM
# highlighter:      rouge
# Permalinks
permalink:        pretty
# Server
url:              https://apeattack.github.io/
enforce_ssl:      apeattack.github.io/
encoding:         UTF-8
host:             127.0.0.1
port:             9001

# Gems
gems:
  - jekyll-sitemap
  - rouge
